name: Deploy Cloudflare Worker

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: cloudflare-worker-production
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy ed-cors-proxy
    runs-on: ubuntu-latest
    environment:
      name: cloudflare-production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        env:
          ALLOWED_ORIGINS: ${{ secrets['ALLOWED_ORIGINS'] }}
          CLOUDFLARE_WORKER_NAME: ${{ secrets['CLOUDFLARE_WORKER_NAME'] }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --name $CLOUDFLARE_WORKER_NAME --var ALLOWED_ORIGINS:$ALLOWED_ORIGINS